spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/kokoo-dev/spring-cloud-repository
          search-paths:
            - /example

server:
  port: 8888